### ISSUE TITLE
RedCornersUSDX

### ISSUE THREAD

**Issue by www97221** [GW8RDI/uSDXOpen#7]
First of all, thank you GW8RD. I have a question: I would like to add an item to the menu using your comment: # define N_ PARAMS 44+4//number of (visible) parameters//G8RDI mod+3 for added visible menu items and enum params_ T also modified switch (id) {//Visible parameters
After the case ADD is completed, the newly added menu item in USDX displays garbled code. I don't know where the problem is

**Comment by BitLoose** [comment]
There are several parameters/defines for the menu system, you'll need to search for all references to the actual memory variable.  I suggest you load the ino file, renamed ...ino.c into MS Visual Studio, it has far better reference tracking support.
I would have to do the same myself as the structure is a little complicated, but it will be a useful exercise if you're going to be editing the code.

**Comment by www97221** [comment]
Thanks you but When I put the added menu at the last item, it will display garbled code, but placing it after one of the menus is normal

**Comment by www97221** [comment]
Is OK搞明白了
